[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9263012031bfa8969e425951c1c08ee6d7213c55"
os = "macos"

    [[Cairomm.download]]
    sha256 = "dc79e98f2606bb377a2de568ff4091524da03d863d5e129f7cee033fc95d4f4d"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.aarch64-apple-darwin-cxx03.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f900c447c1340a95f3940ae144692e7db0fa771"
os = "macos"

    [[Cairomm.download]]
    sha256 = "fed9940e5c4fc17cba05e5b3b47703ef1fcf02e086e225a01fb6f9852b77fa76"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.aarch64-apple-darwin-cxx11.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "488ff9046e6af0597b0a019e0dad9c0b218a332c"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "966ecd70c63f3f23ad995f545cee24fd6a9d627acd3a27560219f8538785315e"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dabba87114756965f6ae645f3ed2e482d1fc237"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "b380f3348fd4e2195d1a0b199b51d5f7a69ea336e958cc2f3f841f36fdb33934"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "854766ae0a75b2fa16dd2bd34f51d9b0d83cf705"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "d32a1d2f022105c417845b6418a0e4b638c48f0de3a4eba4eab62e98177530c3"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.aarch64-linux-musl-cxx03.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f0cdbf5411c6a38a0ae909b330dc65b705b5654"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "a9e01b5fc7a5d6594c21fb4961961eac5f95bf598f13ee9fa823f63de1851491"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.aarch64-linux-musl-cxx11.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cdecf48dd5a19265160fd9f03e5a65c3d1ab631"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "cb182e9ce733c8401b465e14032fd60c2079eede48a9c6dff490568ba7444b47"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a355d5f59d9d2657997f73834a2a67a32e525c98"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "e4a208e1545d5a509a27a90eb8574aebfd8fd7a05b4a3f18e7a4754bdb1e2806"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfb3b67b77256a5df3db5ed41f86029ae27130f4"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "df30c354cab33837007f2b6b068f9cd96734cc3ab0617c4f1db75ec2edeef66d"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d502f862acaedfa260ed3d998cb900638e19d41"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "2ad56a3565830a92549daa4ed318781449be6a0ab5687943f44dc839facb0abc"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db2644145e5f6bc7c5061a48f8db286569702a36"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "47de2f188dcda3ee826ea8e2ec6178c8e43aed7a0ddae490dc754ec72eb1e623"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.i686-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdb55e8af957af1dc9b7cd8e263541acc2ce0fee"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "f398e430e992b789d30583fd53559a3a6b5d950fd15d4859dd0180b5a24d915b"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.i686-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aed31b56b44ccbe9a530d81ba6466d6930eb02b9"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "429067e88c399e72f423877d2007fd4bf5e59413927f38497b00c66d9835be64"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.i686-linux-musl-cxx03.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9afac966d4469a8032277b14668a8f3e1e678f3a"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "2b4269ade6360906a7bcae570c15046738a145a7ec5f0db17d51e007143ee5f2"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.i686-linux-musl-cxx11.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3677d41f1b09bd89bfa2bd8cd64d59601879d457"
os = "windows"

    [[Cairomm.download]]
    sha256 = "d8c1c25998fd51d1a8d6797b64eefb6ea250ced65101234db1e03f2744d3c207"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.i686-w64-mingw32-cxx03.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "845a0fcfa09cad1f5392d45b3d9b2c3915644005"
os = "windows"

    [[Cairomm.download]]
    sha256 = "ec9dc7e23f346a2e82bde1f8fcc6ecd47ca45ec8637858eaecc140a2cb201ac0"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.i686-w64-mingw32-cxx11.tar.gz"
[[Cairomm]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4991a5263dbf90d68bbc95fb68486af051080736"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "cfda7313718b7f771ab2d4d17db787112d6f35953860f220222e36c29ed0816f"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d37becf568313d544ccb63dc15be119a4e9a6bc"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "ad728de1ff5c314229dfed75d1c65ccdda77ea2b05b4f23b851f8fe6765a95d5"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5b28edd043d8e39db5eab1c2ebbaf7eedbc604e"
os = "macos"

    [[Cairomm.download]]
    sha256 = "235d98c61861a9e133d12232d3c669f09d858c5669871c3ac7457a4addd40310"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-apple-darwin-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff411c84d1b58b177dfdf9fd822feb8f24a7fef6"
os = "macos"

    [[Cairomm.download]]
    sha256 = "01278464b91e395e66fc00ea837cf9fc6d3376048a0f3266e724864c7f56ebd9"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-apple-darwin-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31036c08d2c2217bd626a1c17f594287b69b62cb"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "0cabd37addacb803eed31e5c9246c58ec918cf4349888261a3a75d5782c5fd42"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93ce22dfbb0d9c0414a9bb84e29b5cc1af983084"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "9c4968afe003dfb87987919ac2ffc41f0c178d8ef99a1ab0351565d25e5886ae"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8c31486d8a062635bbef3895132ef24ed2164a3"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "e7c517c168823add60c897ce4745128f400d0536f1b3481a0020d198fcb20266"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-linux-musl-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdbe0a01e925ffa6be93d1d234d4ab669291af7d"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "c6aa0645d4c52c5d401c0415a31b7f2220cb3b60159708f41259cda2c2801b77"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-linux-musl-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dceb8e4d91574f0f17ef8fb2dfa8425db47545dd"
os = "freebsd"

    [[Cairomm.download]]
    sha256 = "8803a31d978390d418a7b0f80a9d55b4836b37b7b7d8625cb250adec2f579e83"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b1d1a615fb3622bd26fff68f94b7b788cad0ec4"
os = "freebsd"

    [[Cairomm.download]]
    sha256 = "b522dcbb2578a9f037750eba3e6852b6c8bcdd0f345ff579d351ee2ce2808ec6"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-unknown-freebsd-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5da843e1d9ef7087075cfdae06be172d2a94bda"
os = "windows"

    [[Cairomm.download]]
    sha256 = "63707d8c06b8d19c9d70c04ebfc4cb0df6d85ae076edd9d2a3815567ffb5b790"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8da9452eb2c8c1b2a59ae11edfb7f4f906fb8c3"
os = "windows"

    [[Cairomm.download]]
    sha256 = "577dfb85fcf08e9ef4fce85098e608376034f21e55355b92a7983a19a7aee708"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.16.2+0/Cairomm.v1.16.2.x86_64-w64-mingw32-cxx11.tar.gz"
