[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de130a584792118822a7c4683890187b4460144c"
os = "macos"

    [[Cairomm.download]]
    sha256 = "7015557b8e58c37e748345bb6328e7070fce85ad02a22aeb898f018cdff5193a"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.aarch64-apple-darwin-cxx03.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eb1ad8eed054551d74eb0a5196f207d2fc6c34c"
os = "macos"

    [[Cairomm.download]]
    sha256 = "b62612d4b7034ec3de9592f1be7ee67839eaebbed23e312139ed792ffc581012"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.aarch64-apple-darwin-cxx11.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99aaa4047243097bd5bf206a7a230c9e737cbda7"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "3dc5ae57c1674449dbad6633abd5b53f594098e7e5fdb515c07f580ccfb26eaa"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.aarch64-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a86391404a6a84f8ebe18a5c1d66632436207b74"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "bfab900ab9712ac2fa27331b6486763a606232fe221fcfe055d0d6e6c0195c58"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.aarch64-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fe857467bc66fed5af1abb171e109c70116300a"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "845ad1bbf032a94a6f922d8877c3086435a127bd0de1d7ed9ab92e0b3b3781cf"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.aarch64-linux-musl-cxx03.tar.gz"
[[Cairomm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8621f271d0a5cef036c1018f8d3805f0e42f06eb"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "fcc1821b4732f0ddabd661c9c955a3b075fea3752b569ae356bdf8e6cf4b347d"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.aarch64-linux-musl-cxx11.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da4120520656115786659053300d9ceffcda7845"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "10ae69f745c8fc676fcdd6ef1de3d5b1dd831216faef76afa595b6c9825c0020"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cdd565bf00c03cc190eeccb801142c7ac2b4f72"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "b6db7c5f4857088321e3291b26e2e0d804fc74db37ff388c9f9babfe8d85973b"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97e155ca15277f57889b8eaa949c6ac65b210484"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "5e36abcd6da0fe118cec076db18f7a4bb4977160d10e02140cff1b2a4de6ff4f"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cairomm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03bc8e8141e4d98f96efa1b63311e815c909c5c8"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "60a5163ce48388f7eb7951e5d2cd3b3f9f844eff0707b0aa8a3fd709d80f0d79"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dae0cb361c9fa16d875ad3563c7c4fcdde6ece5"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "cade81b626e6e27ffbb78853d949ac3b80b3ea9647456e1c76a259ed898004a0"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.i686-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f3e42d48515912397168fc0f39bbb8dddb4d8b5"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "d56b555fd7829705114660a498c0c11b63994cff454aed32fb091a8324f01b34"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.i686-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fa845b9b78c536ce99eec15a04c5dc14989be22"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "3959f92547641308307ebd7e0a720b68bffbdb203910cb18d17e7338d7100612"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.i686-linux-musl-cxx03.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f016e4fe9cade0b915633a10b00a7f56feb90a87"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "a55db2cefc422a102d9631768a725da4d837d6a2d9c334f3c2b450738c44afce"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.i686-linux-musl-cxx11.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e60b2e53b43624b95b2537b2ca56b03eb3fe246c"
os = "windows"

    [[Cairomm.download]]
    sha256 = "687bb134cf02e6aa52484b94184183e2493a131d00eaea17e0010e6c2780d9ef"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.i686-w64-mingw32-cxx03.tar.gz"
[[Cairomm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1981971174d40178d9dea737d845a971ddac905f"
os = "windows"

    [[Cairomm.download]]
    sha256 = "dc67a52ba8c155a2ed95ba4bffb55ea50902cfb3f4a520fa54f1807233087744"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.i686-w64-mingw32-cxx11.tar.gz"
[[Cairomm]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebf8aa2f6a1a885c9f884f9085fa28f610fd958a"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "1ce3401102bc272a28c7154463ba30455326b6bf18d15cd9f84f09381922983c"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d363c3d6af90274a5bf3c14986823523cba05a0e"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "17f9f69d2ab0feceb2a05ac164f2545d2b6d1a75333e5ec4ccc9ef8ccc75676d"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcdbc8ebe2f767a8dbfe71a97996d580f5f70c6b"
os = "macos"

    [[Cairomm.download]]
    sha256 = "26de669a934bcab1787c4066eb44b9884237dbda1917697f5ce3386ccbb9a03d"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-apple-darwin-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0227d56ec234f8ea3bb62a36de2361e11997bdad"
os = "macos"

    [[Cairomm.download]]
    sha256 = "543c66ca64660024663e5d022d2949fc878c4c15697ffd1c10baf65f3ea223e4"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-apple-darwin-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbfc6a32b4044cf7a2a061c57474e7b1f7a80054"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "238535c8a3ff7cb4714455589f9e60ea6689cab8744abafd3468d02ea3034dcc"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-linux-gnu-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0071d74106ee1721b0f7504ff0a87b4a803693fb"
libc = "glibc"
os = "linux"

    [[Cairomm.download]]
    sha256 = "9c0c046bc8697db06a407841e951d7ab4f1dccf3bdca0d807f7ebeea15ecde1c"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-linux-gnu-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8759f1e373e098d245696bf46d21f576aad36fec"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "1504401a5a9953c8c5778ea4fd83b2364a1582f88cce2f0449383a3825af7185"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-linux-musl-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8415e893163d1d773f1c5c878e780083616e62c4"
libc = "musl"
os = "linux"

    [[Cairomm.download]]
    sha256 = "80344a2348f2fa936138ce7ff0a962906c3701ceaf883a485dd277d4b4ec159a"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-linux-musl-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af462faf1b087034dd05d46a05e3dad238df71e1"
os = "freebsd"

    [[Cairomm.download]]
    sha256 = "448da50574562a8e9c890dc931b735f3d18423103730d591564dcea9a4dde60c"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f300b8984b7740af198a8aedbfec63fecfe9e90"
os = "freebsd"

    [[Cairomm.download]]
    sha256 = "88a9d3f58936032c5bd5e814827941b9b46c2bb8a629bd0362e49f0fa9ef95d9"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-unknown-freebsd-cxx11.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5daca82d5df4e27b0297f2be1233583a805a42d"
os = "windows"

    [[Cairomm.download]]
    sha256 = "5a78dd730625f542fd2ce654e7f47149ac91196ea9a583b0222f0d0c6a15c035"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cairomm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44cb69e365f9744e3b86509deb75534ce3f97444"
os = "windows"

    [[Cairomm.download]]
    sha256 = "44887d91f80cffbd58b834a6a59ff04bdd5dc5ae1c047a096eb8f9af12e64e64"
    url = "https://github.com/JuliaBinaryWrappers/Cairomm_jll.jl/releases/download/Cairomm-v1.14.4+0/Cairomm.v1.14.4.x86_64-w64-mingw32-cxx11.tar.gz"
